env:
  MAVEN_OPTS: "-XX:MaxPermSize=256m -Xmx1g"
  JAVA_HOME: "/usr/lib/jvm/java-8-openjdk-amd64"

merge:
  commanders:
    - aistomin
  script: |-
    java -version
    mvn -version
    mvn clean install package javadoc:javadoc