dist: bionic
language: java
jdk:
  - oraclejdk15
branches:
  only:
    - master
env:
  global:
    - MAVEN_OPTS="-XX:MaxPermSize=512m -Xmx2g"
    - CODECOV_TOKEN="84279588-6635-4ff4-8f7f-e31b54666093"
script: ./build.sh
