version: 1.0.{build}
skip_tags: true
branches:
  only:
    - master
image: Ubuntu2004
build_script:
  - echo $JAVA_HOME
  - mvn clean install package javadoc:javadoc
  - bash <(curl -s https://codecov.io/bash)